# Generated by Django 5.1.2 on 2024-11-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="preview_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
